name: Tests
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt install libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Rust Setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache Deps
        uses: swatinem/rust-cache@v1
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Format (rustfmt)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
      - name: Lint (clippy)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --release
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
